# Project Information
site_name: mikeCentola->docs()
site_description: Tutorials and Documents by Mike Centola
site_author: Mike Centola
site_url: https://docs.mikecentola.com

# Repository
repo_url: https://github.com/mikecentola/mikecentola.github.io
edit_uri: ''
remote_branch: master

# Copyright
copyright: 'Copyright &copy; 2019 Mike Centola All Rights Reserved'

# Configuration
docs_dir: docs
site_dir: ../docs/

markdown_extensions:
  - admonition
  - footnotes
  - meta

extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/mikecentola'
    - type: 'instagram'
      link: 'https://instagram.com/mikecentola'
    - type: 'github'
      link: 'https://github.com/mikecentola'

plugins:
  - search
  - git-revision-date

# Theme Configuration
theme: 
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'cyan'
  logo: 
    icon: 'tag_faces'
  custom_dir: custom_theme/

# Navigation
nav:
- Home: /
- Docs:
  - Test Tutorial: 'tutorials/test.md'
- Blog: https://mikecentola.com/blog/
- About: https://mikecentola.com/#about