site_name: Mike Centola
site_author: Mike Centola
site_url: https://docs.mikecentola.com
repo_url: https://github.com/mikecentola/mikecentola.github.io
copyright: Copyright (c) 2019 Mike Centola
remote_branch: master
docs_dir: docs
site_dir: ../docs
nav:
  - Home: https://mikecentola.com
  - Tutorials:
    - Test Tutorial: 'tutorials/test.md'

  - About: https://mikecentola.com/#about

theme: 
  name: 'material'
  palette:
    primary: 'grey'
    accent: 'cyan'